# Site settings
title: 'Greg de Lima'
description: 'A&middot;N&middot;A&middot;L&middot;Y&middot;T&middot;I&middot;C&middot;S &nbsp; D&middot;E&middot;V&middot;E&middot;L&middot;O&middot;P&middot;E&middot;R'
url: 'blog.gregdelima.com'
baseurl: ''
google_analytics: 'G-YTMFWGJFEJ'
# disqus_shortname: 'your-disqus-name'


remote_theme: "gd-l/jekyll-uno"
#remote_theme: matthiaslischka/jekyll-uno


excerpt_separator: <!--more-->


author:
  name: 'Greg de Lima'
  email: greg@gregdelima.com
  twitter_username: gregdelima 
  #facebook_username: 
  github_username: gd-l
  linkedin_username:  gregdelima

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache
  
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']